"""
HiCache PP Consistency Protocol Data Structures.

This module defines the protocol data structures for ensuring HiCache consistency
across Pipeline Parallel (PP) ranks. The protocol ensures that all PP ranks
maintain consistent radix tree states through synchronized decision-making
and outcome alignment.

Reference: docs/specs/op-cons/design.md
"""

from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import List, Optional


class HiCacheAction(str, Enum):
    """Actions that can be taken for HiCache control."""

    PREFETCH = "prefetch"
    REVOKE = "revoke"
    SKIP = "skip"


class HiCacheFinalState(str, Enum):
    """Final states of a HiCache operation."""

    COMPLETED = "completed"
    REVOKED = "revoked"
    SKIPPED = "skipped"
    FAILED = "failed"


class HiCacheFailureReason(str, Enum):
    """Reasons for HiCache operation failure."""

    HOST_ALLOC_FAILED = "host_alloc_failed"
    STORAGE_ERROR = "storage_error"
    PROTOCOL_ERROR = "protocol_error"
    MISMATCH = "mismatch"
    TIMEOUT = "timeout"
    PREV_RANK_TIMEOUT = "prev_rank_timeout"
    ALIGNMENT_TIMEOUT = "alignment_timeout"
    ALIGNMENT_MISMATCH = "alignment_mismatch"


class GlobalFailedReason(str, Enum):
    """Reasons for global failure notice."""

    FAILED = "failed"
    CANCELLED = "cancelled"


@dataclass
class HiCacheDecision:
    """
    HiCache control decision generated by rank 0 and propagated to subsequent ranks.

    This is the core control plane message that ensures all PP ranks execute
    the same prefetch/revoke/skip decision for a given request.

    Attributes:
        request_id: Unique identifier for the request.
        seq_id: Request-level monotonically increasing event sequence number,
                generated by rank 0.
        action: The action to take - "prefetch", "revoke", or "skip".
        planned_tokens: Number of tokens planned to prefetch (must be page-aligned).
        token_ids: Specific token sequence to prefetch. Subsequent ranks must use
                   this field for prefetch instead of computing new_input_tokens locally.
        prefix_length: Result of match_prefix() from rank 0, used for verification
                       by subsequent ranks.
        last_hash: Hash value of the prefix end node for tree consistency verification.
    """

    request_id: str
    seq_id: int
    action: HiCacheAction
    planned_tokens: int
    token_ids: List[int]
    prefix_length: int
    last_hash: Optional[str] = None


@dataclass
class HiCacheOutcome:
    """
    Outcome of a HiCache operation, used for cross-rank alignment.

    Each rank produces an outcome after executing a decision. Alignment checks
    ensure that outcomes match across PP ranks before requests can enter forward.

    Attributes:
        request_id: Unique identifier for the request.
        seq_id: Corresponds to the seq_id of the decision.
        source_pp_rank: The PP rank that produced this outcome.
        final_state: Final state - "completed", "revoked", "skipped", or "failed".
        completed_tokens: Number of tokens actually completed (affects radix tree).
        applied_tokens: Number of tokens actually applied to radix tree
                        (the definitive field for consistency).
        local_prefix_length: Local match_prefix result (for consistency verification).
        failure_reason: Reason for failure (only valid when final_state is "failed").
    """

    request_id: str
    seq_id: int
    source_pp_rank: int
    final_state: HiCacheFinalState
    completed_tokens: int
    applied_tokens: int
    local_prefix_length: int
    failure_reason: Optional[HiCacheFailureReason] = None


@dataclass
class GlobalFailedNotice:
    """
    Failure notification broadcast by rank 0 to all ranks.

    When any rank fails, the failure propagates back to rank 0, which then
    broadcasts this notice to trigger global failure convergence.

    Attributes:
        request_id: Unique identifier for the request.
        seq_id: The seq_id of the decision that failed.
        reason: Reason for failure - "failed" or "cancelled".
        source_pp_rank: The PP rank that triggered the failure.
    """

    request_id: str
    seq_id: int
    reason: GlobalFailedReason
    source_pp_rank: int


@dataclass
class ReleaseNotice:
    """
    Resource release instruction broadcast by rank 0.

    Used to clean up protocol state across all ranks when a request completes
    or is aborted.

    Attributes:
        request_id: Unique identifier for the request.
        seq_id: The last decision seq_id for this request.
    """

    request_id: str
    seq_id: int


@dataclass
class HiCacheRequestState:
    """
    Per-request protocol state maintained by HiCacheProtocolManager.

    Tracks the protocol state for a single request across its lifecycle.

    Attributes:
        request_id: Unique identifier for the request.
        latest_decision_seq_id: The most recently received decision's seq_id.
        latest_outcome_seq_id: The most recently completed outcome's seq_id.
        terminal_state: Terminal state - "none", "failed", or "released".
        pending_decision: The decision currently awaiting execution.
        local_outcome: The outcome produced locally for the current decision.
        prev_rank_outcome: The outcome received from the previous rank (rank > 0 only).
    """

    request_id: str
    latest_decision_seq_id: int = -1
    latest_outcome_seq_id: int = -1
    terminal_state: str = "none"  # "none", "failed", "released"
    pending_decision: Optional[HiCacheDecision] = None
    local_outcome: Optional[HiCacheOutcome] = None
    prev_rank_outcome: Optional[HiCacheOutcome] = None


@dataclass
class HiCachePrefetchState(str, Enum):
    """
    Fine-grained prefetch state for tracking progress.

    Used to track the progression of a prefetch operation through its lifecycle.
    """

    DECISION_RECEIVED = "decision_received"  # Decision received, not yet executed
    PREFETCH_STARTED = "prefetch_started"  # Entered ongoing_prefetch, IO in progress
    IO_COMPLETED = "io_completed"  # Remote data arrived in host memory
    TREE_UPDATED = "tree_updated"  # check_prefetch_progress() completed tree update
    OUTCOME_PRODUCED = "outcome_produced"  # HiCacheOutcome generated, ready for alignment


@dataclass
class BatchedHiCacheOutcomes:
    """
    Batched outcomes for efficient transmission.

    For completed/revoked/skipped outcomes (non-failed), outcomes can be
    batched together for transmission to reduce message count.

    Attributes:
        outcomes: List of individual outcomes in this batch.
        batch_id: Optional batch identifier for tracking.
    """

    outcomes: List[HiCacheOutcome] = field(default_factory=list)
    batch_id: Optional[int] = None

    def add(self, outcome: HiCacheOutcome):
        """Add an outcome to this batch."""
        self.outcomes.append(outcome)

    def __len__(self):
        return len(self.outcomes)

    def __iter__(self):
        return iter(self.outcomes)
